### Likelihood function

### Function to evaluate the negative log-likelihood of the multiple cohort stopover model in the HMM framework

# Name: likelihood_cohort
# Objective: To evaluate the negative log-likelihood of the multiple cohort HMM given a set of parameter values and capture histories
# Inputs: param - model specific, will be passed to other functions for structuring
#         X - capture histories, a matrix for each cohort stored in a list
#         arr.dist - distribution on arrivals, distribution and structure
#         model - model to be fitted, parameter structure
# Outputs: lik - negative log-likelihood value

likelihood_cohort <- function(param, X, arr.dist, model)  {
  
  # define constants
  n.cohorts <- length(X)  # number of cohorts
  n <- rep(0, n.cohorts)  # number of individuals in each cohort
  K <- rep(0, n.cohorts)  # number of capture occasions for each cohort
  for (c in 1:n.cohorts)  {
    n[c] <- length(data[[c]][,1])
    K[c] <- length(data[[c]][1,])
  }
  
  # unpack the parameter vector
  param_function <- match.fun(arr.dist)
  params <- param_function(param, model, n.cohorts, n, K)
  HMM <- HMM.str(params, n.cohorts, K)
  
  # storage variables
  lik.cohort <- rep(0, n.cohorts)
  
  # loop over cohorts evaluating likelihood for single cohort
  for (c in 1:n.cohorts)  {
    lik.partial <- 0
    # loop over individuals
    for (i in 1:n[c])  {
      contrib <- HMM$pione[[c]]
      # loop over occasions
      for (k in 1:K[c])  {
        contrib <- contrib %*% HMM$gamma[[c]][,,k]
        contrib <- contrib %*% HMM$pmat[[c]][,,X[[c]][i,k]+1, k]
      }
      # individual contribution
      contrib <- contrib %*% matrix(1, nrow = 3, ncol = 1)
      # add to likelihood for this cohort
      lik.partial <- lik.partial + log(contrib)
    }
    # store likelihood value for cohort
    lik.cohort[c] <- lik.partial
  }
  
  # evaluate full likelihood
  lik <- -sum(lik.cohort)
  
  # return
  return(lik)
}



### Function to return the HMM structures given a list of parameters for the cohort stopover model

# Name: HMM.str
# Objective: To take a list of parameters returned from the arr.dist functions and return the HMM structures for use in the likelihood
# Inputs: param - list of parameters generated by the arr.dist functions
#         n.cohorts - the number of cohorts
#         K - number of capture occasions for each cohort
# Outputs: pione - initial state distributions for each cohort
#          gamma - transition probability matrices for each cohort
#          pmat - observation matrices for each cohort

HMM.str <- function(param, n.cohorts, K)  {
  
  # initial state probabilities
  # state probabilities at time 0, year of tagging
  pione <- list()
  for (c in 1:n.cohorts)  {
    pione[[c]] <- c(1, 0, 0)
  }
  
  # transition probability matrices (state, state, occasion)
  gamma <- list()
  for (c in 1:n.cohorts)  {
    gamma[[c]] <- array(0, dim = c(3, 3, K[c]))
    gamma[[c]][1,1,] <- 1 - param$betastar[[c]]
    gamma[[c]][1,2,] <- param$betastar[[c]]
    gamma[[c]][2,2,] <- param$phi
    gamma[[c]][2,3,] <- 1 - param$phi
    gamma[[c]][3,3,] <- 1
  }
  
  # observation matrices (state, state, capture/not, occasion)
  pmat <- list()
  for (c in 1:n.cohorts)  {
    pmat[[c]] <- array(0, dim = c(3, 3, 2, K[c]))
    pmat[[c]][1,1,1,] <- 1
    pmat[[c]][2,2,1,] <- 1-param$p[[c]]
    pmat[[c]][3,3,1,] <- 1
    pmat[[c]][2,2,2,] <- param$p[[c]]
  }
  
  # return
  return(list('pione' = pione, 'gamma' = gamma, 'pmat' = pmat))
}
  


### Functions to unpack the parameter vector

### Function to unpack the parameter vector - normal distribution on arrivals, shared mean and sd, constant capture, constant survival

# Name: onenormalalldiff_constp_constphi
# Objective: To unpack and transform a vector of parameter values for the multiple cohort stopover model HMM
# Inputs: param - vector of parameter values
#               - [n.cohorts] - log mu for arrival distribution, one per cohort
#               - [n.cohorts] - log sd for arrival distribution, one per cohort
#               - [1] - logit p, constant capture probability, shared across all cohorts 
#               - [1] - logit phi, survival probability, shared across all cohorts
#         n.cohorts - number of cohorts
#         n - vector of observed number of individuals in each cohort
#         K - vector of the number of capture occasions for each cohort
#         min.age - minimum age of return
# Outputs: mu - means for each cohort
#          sd - sd for each cohort
#          beta - arrival probabilities for each cohort
#          betastar - conditional arrival probabilities for each cohort
#          p - capture probabilities
#          phi - survival probabilities

onenormalalldiff_constp_constphi <- function(param, n.cohorts, n, K, min.age = 3)  {
  
  # means
  normal.means <- exp(param[1:n.cohorts])
  
  # sds
  normal.sds <- exp(param[(n.cohorts+1):(2*n.cohorts)])
  
  # arrival probabilities
  beta <- list()
  for (c in 1:n.cohorts)  {
    beta[[c]] <- onenormalbetas(normal.means[c], normal.sds[c], K[c], min.age)
  }
  
  # conditional arrival probabilities
  betastar
  }
}